install:
  tasks:
    - bash: |
        deno lint
        deno run compile

"tab:title":
  silent: true
  tasks:
    - bash: |
        args="$GIT_WP_PROJECT:$GIT_WP_BRANCH"
        for arg in "$@"; do args="${args}:${arg}"; done
        wezterm cli set-tab-title "$(echo "$args" | sed -e 's/^://' -e 's/::*/:/g')"
"vscode:create":
  tasks:
    - bash: |
        filename="$(echo "${GIT_WP_PROJECT}⸬${GIT_WP_BRANCH}" | sed 's#/#⧸#g').code-workspace"
        if [[ ! -f "$filename" ]]; then
          echo '{"folders":[{"path": "."}],"settings":{}}' > "$filename"
        fi
"vscode:open":
  silent: true
  tasks:
    - action: vscode:create
    - bash: |
        filename="$(echo "${GIT_WP_PROJECT}⸬${GIT_WP_BRANCH}" | sed 's#/#⧸#g').code-workspace"
        open "$filename"
